version: "3.9"

services:
  postgres:
    build: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "4g"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
